name: violeta_s_application_2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter:   # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  lottie: ^2.2.0  # or the latest version
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  image_picker: ^1.2.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  http: ^1.1.0
dev_dependencies: 
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
flutter: 
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets: 
    - assets/
    - assets/images/
    - assets/anim/walktalk_running.json
    - env.json
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700

  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # 🚨 CRITICAL FONTS RULE:
  # - DO NOT ADD NEW LOCAL FONTS TO assets/fonts/ 
  # - ONLY USE EXISTING LOCAL FONTS FROM assets/fonts/
