name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npx eslint . --max-warnings=0
      - run: npm run typecheck --if-present || npx tsc --noEmit
      - run: npm test -- --run
      - run: npm run build --if-present
